In [1]:
import numpy as np
import pandas as pd
import re
# import seaborn as sns
from sklearn.metrics.pairwise import euclidean_distances
import warnings
warnings.filterwarnings("ignore")

In [2]:
data=pd.read_csv("C:/Users/HP-PC/Downloads/SpotifySongs.csv")
data.head()
data.iloc[0:75,:]

SongName  \
0                                          Saiyaan Ji   
1                                             Falling   
2                                              Shayad   
3   Malang (Title Track) [From "Malang - Unleash T...   
4                       Genda Phool (feat. Payal Dev)   
..                                                ...   
70                                            unravel   
71                                             ブルーバード   
72                                       Lucid Dreams   
73                                         Experience   
74                                            Element   

                    ArtistName  Popularity  Danceability  Energy  Key  \
0            Yo Yo Honey Singh          62         0.896   0.678    0   
1                Trevor Daniel          84         0.785   0.431   10   
2                       Pritam          72         0.483   0.468    8   
3                   Ved Sharma          68         0.384   0.728    7   
4                      Badshah          67         0.955   0.538    1   
..                         ...         ...           ...     ...  ...   
70  TK from Ling tosite sigure          81         0.447   0.449    2   
71               Ikimonogakari          80         0.772   0.878    2   
72                  Juice WRLD          82         0.905   0.647   10   
73            Ludovico Einaudi          72         0.868   0.479    4   
74                   Pop Smoke          72         0.701   0.554    1   

    Loudness  Mode  Speechiness  Acousticness  Instrumentalness  Liveness  \
0     -2.546     0       0.0815        0.0137          0.000041    0.1100   
1     -8.756     0       0.0364        0.1230          0.000000    0.0887   
2     -7.642     1       0.0341        0.7850          0.000000    0.1520   
3     -6.503     0       0.0623        0.3290          0.000018    0.3290   
4     -8.394     1       0.0734        0.1320          0.001460    0.0704   
..       ...   ...          ...           ...               ...       ...   
70   -10.634     1       0.0376        0.9340          0.961000    0.0697   
71    -4.220     1       0.3240        0.0301          0.000002    0.2510   
72    -5.065     0       0.1070        0.0187          0.000000    0.2820   
73    -6.687     0       0.4450        0.7030          0.000000    0.1020   
74    -5.909     1       0.1870        0.2170          0.000001    0.4190   

    Valence    Tempo  Duration_ms  
0    0.6040  130.024       205450  
1    0.2360  127.085       159382  
2    0.3190  135.864       247941  
3    0.3110  156.396       287374  
4    0.8370  116.977       170769  
..      ...      ...          ...  
70   0.0360   92.468       315427  
71   0.3050   61.311       135747  
72   0.3670  130.970       190534  
73   0.7760  133.928       115200  
74   0.0634   97.129       235187  

[75 rows x 15 columns]

In [3]:
data.shape

(3731, 15)

In [4]:
data.isnull().sum().to_frame()

0
SongName          0
ArtistName        0
Popularity        0
Danceability      0
Energy            0
Key               0
Loudness          0
Mode              0
Speechiness       0
Acousticness      0
Instrumentalness  0
Liveness          0
Valence           0
Tempo             0
Duration_ms       0

In [5]:
data.drop(['Popularity','Duration_ms',],axis=1,inplace=True)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3731 entries, 0 to 3730
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   SongName          3731 non-null   object 
 1   ArtistName        3731 non-null   object 
 2   Danceability      3731 non-null   float64
 3   Energy            3731 non-null   float64
 4   Key               3731 non-null   int64  
 5   Loudness          3731 non-null   float64
 6   Mode              3731 non-null   int64  
 7   Speechiness       3731 non-null   float64
 8   Acousticness      3731 non-null   float64
 9   Instrumentalness  3731 non-null   float64
 10  Liveness          3731 non-null   float64
 11  Valence           3731 non-null   float64
 12  Tempo             3731 non-null   float64
dtypes: float64(9), int64(2), object(2)
memory usage: 379.1+ KB


In [7]:
# data['SongName'].value_counts().to_frame()

In [8]:
from sklearn.cluster import KMeans
import numpy as np

def clustering (column_name):
    # column_name = "Danceability"
    data1 = data[column_name].values.reshape(-1, 1)

    # Choose the number of clusters
    num_clusters = 3

    # Create a KMeans instance and fit it to the data
    kmeans = KMeans(n_clusters=num_clusters)
    kmeans.fit(data1)

    # Get cluster labels assigned to each data point
    cluster_labels = kmeans.labels_

    # Print the cluster labels
    data[column_name]=cluster_labels

In [9]:
# clustering("Danceability")
# clustering("Energy")
# clustering("Key")
# clustering("Speechiness")
# clustering("Acousticness")
# clustering("Instrumentalness")
# clustering("Valence")
# clustering("Tempo")
# clustering("Liveness")
# clustering("Loudness")

In [10]:
data.shape

(3731, 13)

In [11]:
# from sklearn.cluster import KMeans
# import numpy as np
# import pandas as pd

# # Generate example data
# data = {
#     "Danceability": np.random.rand(10),
#     "Energy": np.random.rand(10),
#     "Valence": np.random.rand(10)
# }
# df = pd.DataFrame(data)

# def clustering(df, num_clusters=3):
#     cluster_matrix = np.zeros((len(df), num_clusters), dtype=int)

#     for i, column_name in enumerate(df.columns):
#         data = df[column_name].values.reshape(-1, 1)

# #         kmeans = KMeans(n_clusters=num_clusters)
#         kmeans.fit(data)

#         cluster_labels = kmeans.labels_
#         cluster_matrix[:, i] = cluster_labels

#     return cluster_matrix

# cluster_matrix = clustering(df)
# print("Cluster Matrix:")
# print(cluster_matrix)

In [12]:
data['ID']=np.arange(1,data.shape[0]+1)

In [28]:

data["Danceability"]=data["Danceability"].apply(str)
data["Energy"]=data["Energy"].apply(str)
data["Loudness"]=data["Loudness"].apply(str)
data["Speechiness"]=data["Speechiness"].apply(str)
data["Acousticness"]=data["Acousticness"].apply(str)
data["Instrumentalness"]=data["Instrumentalness"].apply(str)
data["Valence"]=data["Valence"].apply(str)
data["Tempo"]=data["Tempo"].apply(str)
data["Liveness"]=data["Liveness"].apply(str)
data["Loudness"]=data["Loudness"].apply(str)
data["Key"]=data["Key"].apply(str)

In [30]:
data["tag"]=data["Danceability"]+data["Energy"]+data["Loudness"]+data["Speechiness"]+data["Acousticness"]+data["Instrumentalness"]+data["Valence"]+data["Tempo"]+data["Liveness"]+data["Loudness"]+data["Key"]

In [36]:
song=pd.DataFrame({"SongName":data["SongName"],"ArtistName":data["ArtistName"],"tag":data["tag"]})
# 

In [37]:
song.head()

SongName         ArtistName  \
0                                         Saiyaan Ji  Yo Yo Honey Singh   
1                                            Falling      Trevor Daniel   
2                                             Shayad             Pritam   
3  Malang (Title Track) [From "Malang - Unleash T...         Ved Sharma   
4                      Genda Phool (feat. Payal Dev)            Badshah   

                                                 tag  
0  0.8960.678-2.5460.08150.01374.1e-050.604130.02...  
1  0.7850.431-8.7560.03640.1230.00.236127.0850.08...  
2  0.4830.468-7.6420.03410.7850.00.319135.8640.15...  
3  0.3840.728-6.5030.06230.3291.85e-050.311156.39...  
4  0.9550.538-8.3940.07340.1320.001460.837116.977...

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
cv.fit_transform(song["tag"])
vector=cv.fit_transform(song["tag"]).toarray()

In [40]:
vector[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [41]:
from sklearn.metrics.pairwise import cosine_similarity
similarityMatrix=cosine_similarity(vector)
print(similarityMatrix)

[[1.         0.         0.         ... 0.         0.         0.07412493]
 [0.         1.         0.2        ... 0.         0.         0.        ]
 [0.         0.2        1.         ... 0.         0.         0.08451543]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.07412493 0.         0.08451543 ... 0.         0.         1.        ]]


In [14]:
# from sklearn.metrics.pairwise import cosine_similarity

# song_attr= data[['Danceability','Energy','Key','Loudness','Mode','Speechiness','Acousticness','Instrumentalness','Liveness','Valence','Tempo']].values

# similarityMatrix=cosine_similarity(song_attr)
# print(similarityMatrix)

[[1.         0.99572    0.99755489 ... 0.998567   0.99729157 0.98358289]
 [0.99572    1.         0.99968656 ... 0.99921707 0.9973598  0.99134988]
 [0.99755489 0.99968656 1.         ... 0.9998288  0.99809925 0.99017108]
 ...
 [0.998567   0.99921707 0.9998288  ... 1.         0.99860706 0.98963275]
 [0.99729157 0.9973598  0.99809925 ... 0.99860706 1.         0.99408455]
 [0.98358289 0.99134988 0.99017108 ... 0.98963275 0.99408455 1.        ]]


In [42]:
similarityMatrix.shape

(3731, 3731)

In [16]:
list(enumerate(similarityMatrix[0]))

[(0, 0.9999999999999997),
 (1, 0.9957200049536643),
 (2, 0.9975548873764891),
 (3, 0.9987440514325595),
 (4, 0.9985683055632528),
 (5, 0.9974925624360237),
 (6, 0.9990303271267811),
 (7, 0.9934252584051529),
 (8, 0.9994917284961766),
 (9, 0.9980595551811903),
 (10, 0.9996715826691822),
 (11, 0.9985523401832421),
 (12, 0.9987604624654219),
 (13, 0.9985049268776918),
 (14, 0.9997572222189943),
 (15, 0.9981689890118354),
 (16, 0.9972423569083377),
 (17, 0.995643013472273),
 (18, 0.9972423569083377),
 (19, 0.9982053873482526),
 (20, 0.9982053873482526),
 (21, 0.9856692141121144),
 (22, 0.9943891169595341),
 (23, 0.9978360203839008),
 (24, 0.9999482852482621),
 (25, 0.9999482852482621),
 (26, 0.9993794433272457),
 (27, 0.9900754469551595),
 (28, 0.9904726816613265),
 (29, 0.9929590253597455),
 (30, 0.997846714076111),
 (31, 0.9998504287903472),
 (32, 0.9992454396704945),
 (33, 0.9964411379437822),
 (34, 0.9877880639831037),
 (35, 0.996851088412543),
 (36, 0.9980595551811903),
 (37, 0.997438

In [50]:
# .function for the recommendation 
def recomendation(song):
    song_ID=data[data["SongName"]==song].index[0]  # returns song ID  in dataframe 
    distance=similarityMatrix[song_ID]
    song_list=sorted(list(enumerate(distance)) ,reverse=True,key=lambda x:x[1])[1:6]
    for A in song_list:
        print("song Name:",data.iloc[A[0]].SongName,"Artsit name:", data.iloc[A[0]].ArtistName)
    

In [52]:
recomendation("Love Again")

song Name: SugarCrash! Artsit name: ElyOtto
song Name: Love Again Artsit name: Dua Lipa
song Name: Do You Mean Artsit name: The Chainsmokers
song Name: Centuries Artsit name: Fall Out Boy
song Name: u love u (with Tate McRae) Artsit name: blackbear
